import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from '@/Providers/AuthProvider'
import { poppins } from '@/Utils/Font'
import Navbar from '@/shareComponents/Navbar';

export const metadata = {
   title: "LegalCo",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={poppins.className}>
          <main className='min-h-[100vh]'>
            {children}
          </main>
        </body>
      </AuthProvider>
    </html>
  )
}
