import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/Providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "LegalCo",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <AuthProvider>
            <body className={inter.className}>{children}</body>
         </AuthProvider>
      </html>
   );
}
